name: Tests

on:
  push:
    branches:
    - main
    - dev
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-20.04

    steps:
    - name: Say hello world
      run: echo "Welcome to the Github Actions workshop !"

  unit-test:
    runs-on: ubuntu-20.04
    
    steps:
    - name: unit-test
      run: |
        make tests_run
        make coverage